- id: markdownlint
  name: Markdownlint
  description: Run markdownlint on your Markdown files
  entry: mdl
  language: ruby
  files: \.(md|mdown|markdown)$
  language_version: 3.3.0

- id: markdownlint_docker
  name: Markdownlint Docker
  description: Run markdown lint on your Markdown files using the project docker image
  language: docker_image
  files: \.(md|mdown|markdown)$
  entry: markdownlint/markdownlint
