AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'omnibus/bin/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 80

Metrics:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/LineEndConcatenation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '{}'
    '%i': '{}'
    '%I': '{}'
    '%w': '{}'
    '%W': '{}'
    '%r': '{}'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/OptionalBooleanParameter:
  Enabled: false

# once we have a customizable line-end concat,
# then this will be be useful
Style/StringConcatenation:
  Enabled: false

Style/Lambda:
  EnforcedStyle: lambda

# we do this a lot. it's very rubyish
Style/MultilineBlockChain:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
